# Generated by Django 3.1.1 on 2020-09-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='followUpDate',
            field=models.DateField(),
        ),
    ]
