# Generated by Django 3.1.1 on 2020-09-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20200920_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='followUpDate',
            field=models.DateTimeField(),
        ),
    ]
