# Generated by Django 3.1.1 on 2021-05-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_auto_20210421_1030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investigations',
            new_name='Investigation',
        ),
    ]
