# Generated by Django 3.1.1 on 2020-10-01 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_auto_20200929_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbidities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry1', models.CharField(blank=True, max_length=150, null=True)),
                ('entry2', models.CharField(blank=True, max_length=150, null=True)),
                ('entry3', models.CharField(blank=True, max_length=150, null=True)),
                ('entry4', models.CharField(blank=True, max_length=150, null=True)),
                ('entry5', models.CharField(blank=True, max_length=150, null=True)),
                ('entry6', models.CharField(blank=True, max_length=150, null=True)),
                ('entry7', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Comorbidities',
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry1', models.CharField(blank=True, max_length=150, null=True)),
                ('entry2', models.CharField(blank=True, max_length=150, null=True)),
                ('entry3', models.CharField(blank=True, max_length=150, null=True)),
                ('entry4', models.CharField(blank=True, max_length=150, null=True)),
                ('entry5', models.CharField(blank=True, max_length=150, null=True)),
                ('entry6', models.CharField(blank=True, max_length=150, null=True)),
                ('entry7', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Complaints',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry1', models.CharField(blank=True, max_length=150, null=True)),
                ('entry2', models.CharField(blank=True, max_length=150, null=True)),
                ('entry3', models.CharField(blank=True, max_length=150, null=True)),
                ('entry4', models.CharField(blank=True, max_length=150, null=True)),
                ('entry5', models.CharField(blank=True, max_length=150, null=True)),
                ('entry6', models.CharField(blank=True, max_length=150, null=True)),
                ('entry7', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Diagnosis',
            },
        ),
        migrations.CreateModel(
            name='Investigations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry1', models.CharField(blank=True, max_length=150, null=True)),
                ('entry2', models.CharField(blank=True, max_length=150, null=True)),
                ('entry3', models.CharField(blank=True, max_length=150, null=True)),
                ('entry4', models.CharField(blank=True, max_length=150, null=True)),
                ('entry5', models.CharField(blank=True, max_length=150, null=True)),
                ('entry6', models.CharField(blank=True, max_length=150, null=True)),
                ('entry7', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Comorbidities',
            },
        ),
        migrations.CreateModel(
            name='PhysicalExams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry1', models.CharField(blank=True, max_length=150, null=True)),
                ('entry2', models.CharField(blank=True, max_length=150, null=True)),
                ('entry3', models.CharField(blank=True, max_length=150, null=True)),
                ('entry4', models.CharField(blank=True, max_length=150, null=True)),
                ('entry5', models.CharField(blank=True, max_length=150, null=True)),
                ('entry6', models.CharField(blank=True, max_length=150, null=True)),
                ('entry7', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Physical Examinations',
            },
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry1', models.CharField(blank=True, max_length=150, null=True)),
                ('entry2', models.CharField(blank=True, max_length=150, null=True)),
                ('entry3', models.CharField(blank=True, max_length=150, null=True)),
                ('entry4', models.CharField(blank=True, max_length=150, null=True)),
                ('entry5', models.CharField(blank=True, max_length=150, null=True)),
                ('entry6', models.CharField(blank=True, max_length=150, null=True)),
                ('entry7', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Remarks',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry1', models.CharField(blank=True, max_length=150, null=True)),
                ('entry2', models.CharField(blank=True, max_length=150, null=True)),
                ('entry3', models.CharField(blank=True, max_length=150, null=True)),
                ('entry4', models.CharField(blank=True, max_length=150, null=True)),
                ('entry5', models.CharField(blank=True, max_length=150, null=True)),
                ('entry6', models.CharField(blank=True, max_length=150, null=True)),
                ('entry7', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Treatment',
            },
        ),
        migrations.RemoveField(
            model_name='visit',
            name='comorbidities',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='complaints',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='investigations',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='physicalExams',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='vitals',
        ),
        migrations.AddField(
            model_name='vitals',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.visit'),
        ),
        migrations.AlterField(
            model_name='mergedvisits',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='visits.visit'),
        ),
        migrations.AlterField(
            model_name='mergedvisits',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='visits.visit'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='followUpDate',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.AddField(
            model_name='treatment',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.visit'),
        ),
        migrations.AddField(
            model_name='remarks',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.visit'),
        ),
        migrations.AddField(
            model_name='physicalexams',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.visit'),
        ),
        migrations.AddField(
            model_name='investigations',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.visit'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.visit'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.visit'),
        ),
        migrations.AddField(
            model_name='comorbidities',
            name='visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.visit'),
        ),
    ]
