# Generated by Django 3.1.1 on 2020-10-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_auto_20201001_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigations',
            options={'verbose_name_plural': 'Investigations'},
        ),
    ]
