# Generated by Django 3.1.1 on 2020-10-18 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_dateofbirth'),
        ('visits', '0007_auto_20201004_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedvisits',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
