# Generated by Django 3.1.1 on 2020-10-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0008_mergedvisits_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergedvisits',
            name='patient',
        ),
    ]
