# Generated by Django 3.1.1 on 2020-10-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0009_remove_mergedvisits_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigations',
            name='entry1',
        ),
        migrations.RemoveField(
            model_name='investigations',
            name='entry2',
        ),
        migrations.RemoveField(
            model_name='investigations',
            name='entry3',
        ),
        migrations.RemoveField(
            model_name='investigations',
            name='entry4',
        ),
        migrations.RemoveField(
            model_name='investigations',
            name='entry5',
        ),
        migrations.RemoveField(
            model_name='investigations',
            name='entry6',
        ),
        migrations.RemoveField(
            model_name='investigations',
            name='entry7',
        ),
        migrations.CreateModel(
            name='InvestigationResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry1', models.CharField(blank=True, max_length=150, null=True)),
                ('entry2', models.CharField(blank=True, max_length=150, null=True)),
                ('entry3', models.CharField(blank=True, max_length=150, null=True)),
                ('entry4', models.CharField(blank=True, max_length=150, null=True)),
                ('entry5', models.CharField(blank=True, max_length=150, null=True)),
                ('entry6', models.CharField(blank=True, max_length=150, null=True)),
                ('entry7', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('investigation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.investigations')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry1', models.CharField(blank=True, max_length=150, null=True)),
                ('entry2', models.CharField(blank=True, max_length=150, null=True)),
                ('entry3', models.CharField(blank=True, max_length=150, null=True)),
                ('entry4', models.CharField(blank=True, max_length=150, null=True)),
                ('entry5', models.CharField(blank=True, max_length=150, null=True)),
                ('entry6', models.CharField(blank=True, max_length=150, null=True)),
                ('entry7', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('investigation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.investigations')),
            ],
        ),
    ]
