# Generated by Django 3.1.1 on 2020-10-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0010_auto_20201024_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='procedureName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
