# Generated by Django 3.1.1 on 2020-10-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0011_payment_procedurename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
