# Generated by Django 3.1.1 on 2020-12-06 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0012_auto_20201031_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigationrequest',
            name='entry2',
        ),
        migrations.RemoveField(
            model_name='investigationrequest',
            name='entry3',
        ),
        migrations.RemoveField(
            model_name='investigationrequest',
            name='entry4',
        ),
        migrations.RemoveField(
            model_name='investigationrequest',
            name='entry5',
        ),
        migrations.RemoveField(
            model_name='investigationrequest',
            name='entry6',
        ),
        migrations.RemoveField(
            model_name='investigationrequest',
            name='entry7',
        ),
        migrations.RemoveField(
            model_name='investigationresults',
            name='entry2',
        ),
        migrations.RemoveField(
            model_name='investigationresults',
            name='entry3',
        ),
        migrations.RemoveField(
            model_name='investigationresults',
            name='entry4',
        ),
        migrations.RemoveField(
            model_name='investigationresults',
            name='entry5',
        ),
        migrations.RemoveField(
            model_name='investigationresults',
            name='entry6',
        ),
        migrations.RemoveField(
            model_name='investigationresults',
            name='entry7',
        ),
        migrations.AlterField(
            model_name='investigationrequest',
            name='investigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.investigations'),
        ),
        migrations.AlterField(
            model_name='investigationresults',
            name='investigation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.investigationrequest'),
        ),
    ]
