# Generated by Django 3.1.1 on 2020-12-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0013_auto_20201206_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigationrequest',
            old_name='entry1',
            new_name='test',
        ),
        migrations.AddField(
            model_name='investigationrequest',
            name='results',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='InvestigationResults',
        ),
    ]
