from django.urls import path

from .views import (
    CreateNewVisitAPIView,
    AllPatientVisitsListAPIView,
    ActiveVisitsListAPIView,
    RetrieveVisitAPIView,
    UpdateVisitAPIView,
    DeleteVisitAPIView,
    getVisitsByDateAPIView,
    FollowUpVisitsAPIView,
    CreateSessionPaymentInfoAPIView,
    getSessionPaymentsListAPIView,
    RetrieveUpdateDeleteSessionPaymentAPIView,
    CreateSessionComplaintsAPIView,
    GetSessionComplaintsAPIView,
    RetrieveUpdateDeleteSessionComplaintsAPIView,
    CreateSessionPhycExamsAPIView,
    GetSessionPhycExamsAPIView,
    RetrieveUpdateDeleteSessionPhycExamsAPIView,
    CreateSessionComorbiditiesAPIView,
    GetSessionComorbiditiesAPIView,
    RetrieveUpdateDeleteSessionComorbiditiesAPIView,
    CreateSessionInvestigationsAPIView,
    GetSessionInvestigationsAPIView,
    RetrieveUpdateDeleteSessionInvestigationsAPIView,
    CreateSessionDiagnosisAPIView,
    GetSessionDiagnosisAPIView,
    RetrieveUpdateDeleteSessionDiagnosisAPIView,
    CreateSessionTreatmentAPIView,
    GetSessionTreatmentAPIView,
    RetrieveUpdateDeleteSessionTreatmentAPIView,
    CreateSessionRemarksAPIView,
    GetSessionRemarksAPIView,
    RetrieveUpdateDeleteSessionRemarksAPIView
)

urlpatterns = [
    path('create/<int:patient_pk>', CreateNewVisitAPIView.as_view()),
    path('patient/visits/history/<int:patient_pk>', AllPatientVisitsListAPIView.as_view()),
    path('list/active', ActiveVisitsListAPIView.as_view()),
    path('list/follow-up', FollowUpVisitsAPIView.as_view()),
    path('list/by-date', getVisitsByDateAPIView.as_view()),
    path('session/details/get/<int:pk>', RetrieveVisitAPIView.as_view()),
    path('session/details/update/<int:visit_pk>', UpdateVisitAPIView.as_view()),
    path('session/details/delete/<int:pk>', DeleteVisitAPIView.as_view()),
    path('payment/create/<int:visit_pk>', CreateSessionPaymentInfoAPIView.as_view()),
    path('payments/list/<int:visit_pk>', getSessionPaymentsListAPIView.as_view()),
    path('payment/details/<int:pk>', RetrieveUpdateDeleteSessionPaymentAPIView.as_view()),
    path('complaints/create/<int:visit_pk>', CreateSessionComplaintsAPIView.as_view()),
    path('complaints/details/<int:visit_pk>', GetSessionComplaintsAPIView.as_view()),
    path('complaints/update/<int:pk>', RetrieveUpdateDeleteSessionComplaintsAPIView.as_view()),
    path('physc-exams/create/<int:visit_pk>', CreateSessionPhycExamsAPIView.as_view()),
    path('physc-exams/details/<int:visit_pk>', GetSessionPhycExamsAPIView.as_view()),
    path('physc-exams/update/<int:pk>', RetrieveUpdateDeleteSessionPhycExamsAPIView.as_view()),
    path('comorbidities/create/<int:visit_pk>', CreateSessionComorbiditiesAPIView.as_view()),
    path('comorbidities/details/<int:visit_pk>', GetSessionComorbiditiesAPIView.as_view()),
    path('comorbidities/update/<int:pk>', RetrieveUpdateDeleteSessionComorbiditiesAPIView.as_view()),
    path('investigations/create/<int:visit_pk>', CreateSessionInvestigationsAPIView.as_view()),
    path('investigations/details/<int:visit_pk>', GetSessionInvestigationsAPIView.as_view()),
    path('investigations/update/<int:pk>', RetrieveUpdateDeleteSessionInvestigationsAPIView.as_view()),
    path('diagnosis/create/<int:visit_pk>', CreateSessionDiagnosisAPIView.as_view()),
    path('diagnosis/details/<int:visit_pk>', GetSessionDiagnosisAPIView.as_view()),
    path('diagnosis/update/<int:pk>', RetrieveUpdateDeleteSessionDiagnosisAPIView.as_view()),
    path('treatment/create/<int:visit_pk>', CreateSessionTreatmentAPIView.as_view()),
    path('treatment/details/<int:visit_pk>', GetSessionTreatmentAPIView.as_view()),
    path('treatment/update/<int:pk>', RetrieveUpdateDeleteSessionTreatmentAPIView.as_view()),
    path('remarks/create/<int:visit_pk>', CreateSessionRemarksAPIView.as_view()),
    path('remarks/details/<int:visit_pk>', GetSessionRemarksAPIView.as_view()),
    path('remarks/update/<int:pk>', RetrieveUpdateDeleteSessionRemarksAPIView.as_view()),
]
