from django.urls import path

from .views import (
    CreateNewVisitAPIView,
    ActiveVisitsListAPIView,
    RetrieveVisitAPIView,
    UpdateVisitAPIView,
    DeleteVisitAPIView,
    getVisitsByDateAPIView,
    FollowUpVisitsAPIView,
    CreateSessionPaymentInfoAPIView,
    getSessionPaymentsListAPIView,
    RetrieveUpdateDeleteSessionPaymentAPIView,
    CreateSessionComplaintsAPIView,
    GetSessionComplaintsAPIView,
    RetrieveUpdateDeleteSessionComplaintsAPIView,
    CreateSessionPhycExamsAPIView,
    GetSessionPhycExamsAPIView,
    RetrieveUpdateDeleteSessionPhycExamsAPIView,
    CreateSessionComorbiditiesAPIView,
    GetSessionComorbiditiesAPIView,
    RetrieveUpdateDeleteSessionComorbiditiesAPIView,
    CreateSessionInvestigationsAPIView,
    GetSessionInvestigationsAPIView,
    RetrieveUpdateDeleteSessionInvestigationAPIView,
    CreateSessionDiagnosisAPIView,
    GetSessionDiagnosisAPIView,
    RetrieveUpdateDeleteSessionDiagnosisAPIView,
    CreateSessionTreatmentAPIView,
    GetSessionTreatmentAPIView,
    RetrieveUpdateDeleteSessionTreatmentAPIView,
    CreateSessionRemarksAPIView,
    GetSessionRemarksAPIView,
    RetrieveUpdateDeleteSessionRemarksAPIView,
    GetComplaintsSuggestionsAPIView,
    GetPhysicalExamsSuggestionsAPIView,
    GetComorbiditiesSuggestionsAPIView,
    GetInvestigationRequestSuggestionsAPIView,
    GetInvestigationResultsSuggestionsAPIView,
    GetDiagnosisSuggestionsAPIView,
    GetTreatmentSuggestionsAPIView,
    GetOpenFollowUpAppointmentsList,
    getPreviousMergedSessionsAPIView,
    getNextMergedSessionsAPIView,
    MergeSessionsAPIView,
    GetLabResultsSessionsAPIView,
    GetCashReportAPIView,
    CreateSessionVitalsAPIView,
    GetSessionVitalsAPIView,
    RetrieveUpdateDeleteSessionVitalsAPIView,
    GetSuspendedAppointmentsList,
    RetrieveLastPatientVisitsAPIView,
    CreateAppointmentAPIView,
    PatientAllVisitsAPIView,
    CreateSessionPrescriptionAPIView,
    GetSessionPrescriptionAPIView,
    RetrieveUpdateDeleteSessionPrescriptionAPIView,
    GetPrescriptionSuggestionsAPIView
)

urlpatterns = [
    path('create/<int:patient_pk>', CreateNewVisitAPIView.as_view()),
    path('list/active', ActiveVisitsListAPIView.as_view()),
    path('list/follow-up', FollowUpVisitsAPIView.as_view()),
    path('list/by-date', getVisitsByDateAPIView.as_view()),
    path('patient/<int:patient_pk>', RetrieveLastPatientVisitsAPIView.as_view()),
    path('session/details/<int:pk>', RetrieveVisitAPIView.as_view()),
    path('session/details/update/<int:visit_pk>', UpdateVisitAPIView.as_view()),
    path('session/details/delete/<int:pk>', DeleteVisitAPIView.as_view()),
    path('payment/create/<int:visit_pk>', CreateSessionPaymentInfoAPIView.as_view()),
    path('payments/list/<int:visit_pk>', getSessionPaymentsListAPIView.as_view()),
    path('payment/details/<int:pk>', RetrieveUpdateDeleteSessionPaymentAPIView.as_view()),
    path('complaints/create/<int:visit_pk>', CreateSessionComplaintsAPIView.as_view()),
    path('complaints/list/<int:visit_pk>', GetSessionComplaintsAPIView.as_view()),
    path('complaints/delete/<int:pk>', RetrieveUpdateDeleteSessionComplaintsAPIView.as_view()),
    path('physc-exams/create/<int:visit_pk>', CreateSessionPhycExamsAPIView.as_view()),
    path('physc-exams/list/<int:visit_pk>', GetSessionPhycExamsAPIView.as_view()),
    path('physc-exams/delete/<int:pk>', RetrieveUpdateDeleteSessionPhycExamsAPIView.as_view()),
    path('comorbidities/create/<int:visit_pk>', CreateSessionComorbiditiesAPIView.as_view()),
    path('comorbidities/list/<int:visit_pk>', GetSessionComorbiditiesAPIView.as_view()),
    path('comorbidities/delete/<int:pk>', RetrieveUpdateDeleteSessionComorbiditiesAPIView.as_view()),
    path('investigations/create/<int:visit_pk>', CreateSessionInvestigationsAPIView.as_view()),
    path('investigations/list/<int:visit_pk>', GetSessionInvestigationsAPIView.as_view()),
    path('investigations/update/<int:pk>', RetrieveUpdateDeleteSessionInvestigationAPIView.as_view()),
    path('investigations/delete/<int:pk>', RetrieveUpdateDeleteSessionInvestigationAPIView.as_view()),
    path('diagnosis/create/<int:visit_pk>', CreateSessionDiagnosisAPIView.as_view()),
    path('diagnosis/list/<int:visit_pk>', GetSessionDiagnosisAPIView.as_view()),
    path('diagnosis/delete/<int:pk>', RetrieveUpdateDeleteSessionDiagnosisAPIView.as_view()),
    path('treatment/create/<int:visit_pk>', CreateSessionTreatmentAPIView.as_view()),
    path('treatment/list/<int:visit_pk>', GetSessionTreatmentAPIView.as_view()),
    path('treatment/delete/<int:pk>', RetrieveUpdateDeleteSessionTreatmentAPIView.as_view()),
    path('remarks/create/<int:visit_pk>', CreateSessionRemarksAPIView.as_view()),
    path('remarks/details/<int:visit_pk>', GetSessionRemarksAPIView.as_view()),
    path('remarks/update/<int:pk>', RetrieveUpdateDeleteSessionRemarksAPIView.as_view()),
    path('complaints/suggestions', GetComplaintsSuggestionsAPIView.as_view()),
    path('phyc-exams/suggestions', GetPhysicalExamsSuggestionsAPIView.as_view()),
    path('comorbidities/suggestions', GetComorbiditiesSuggestionsAPIView.as_view()),
    path('investigations/request/suggestions', GetInvestigationRequestSuggestionsAPIView.as_view()),
    path('investigations/results/suggestions', GetInvestigationResultsSuggestionsAPIView.as_view()),
    path('diagnosis/suggestions', GetDiagnosisSuggestionsAPIView.as_view()),
    path('treatment/suggestions', GetTreatmentSuggestionsAPIView.as_view()),
    path('follow-up/open/list/<int:patient_pk>', GetOpenFollowUpAppointmentsList.as_view()),
    path('merged/previous/<int:visit_pk>', getPreviousMergedSessionsAPIView.as_view()),
    path('merged/next/<int:visit_pk>', getNextMergedSessionsAPIView.as_view()),
    path('merge', MergeSessionsAPIView.as_view()),
    path('list/lab-results', GetLabResultsSessionsAPIView.as_view()),
    path('cash-report', GetCashReportAPIView.as_view()),
    path('vitals/create/<int:visit_pk>', CreateSessionVitalsAPIView.as_view()),
    path('vitals/details/<int:visit_pk>', GetSessionVitalsAPIView.as_view()),
    path('vitals/update/<int:pk>', RetrieveUpdateDeleteSessionVitalsAPIView.as_view()),
    path('patient/visits/suspended/<int:patient_pk>', GetSuspendedAppointmentsList.as_view()),
    path('appointment/create/<int:patient_pk>', CreateAppointmentAPIView.as_view()),
    path('list/of-patient/<int:patient_pk>', PatientAllVisitsAPIView.as_view()),
    path('prescription/create/<int:visit_pk>', CreateSessionPrescriptionAPIView.as_view()),
    path('prescription/list/<int:visit_pk>', GetSessionPrescriptionAPIView.as_view()),
    path('prescription/delete/<int:pk>', RetrieveUpdateDeleteSessionPrescriptionAPIView.as_view()),
    path('prescription/suggestions', GetPrescriptionSuggestionsAPIView.as_view())
]
