# Generated by Django 3.1.1 on 2020-09-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.IntegerField(blank=True, null=True)),
                ('firstName', models.CharField(blank=True, max_length=50, null=True)),
                ('middleName', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('mainPhoneNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('alternativePhoneNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('subCounty', models.CharField(blank=True, max_length=50, null=True)),
                ('estateOrArea', models.CharField(blank=True, max_length=50, null=True)),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
