# Generated by Django 3.1.1 on 2021-05-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
