# Generated by Django 3.1.1 on 2020-09-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patientID',
            new_name='patientRegistrationNumber',
        ),
    ]
