# Generated by Django 3.1.1 on 2021-05-16 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20210515_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
