# Generated by Django 3.1.1 on 2020-10-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200929_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
