# Generated by Django 3.1.1 on 2020-11-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientRegistrationNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
