# Generated by Django 3.1.1 on 2021-05-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20201103_1546'),
        ('patients', '0003_auto_20210516_0051'),
    ]

    operations = [
    ]
